<?php
/**
* English file for plugin site_search
*
* @package wolf
* @subpackage site_search
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/


return array(
/** SiteSearchController.php */ 
'The settings have been saved.' => 'The settings have been saved.', 
/** enable.php FOR RESULTS SNIPPET */
'Please enter a search term.' => 'Please enter a search term.', 
'Displaying results' => 'Displaying results', 
'of' => 'of', 
'matches' => 'matches', 
/** index.php */ 
'Site search' => 'Site search', 
'Provides a basic search function with boolean support' => 'Provides a basic search function with boolean support', 
'Please enter a valid search term. It should have at least '.$min_wordlength.' characters and should not contain special characters.' => 'Please enter a valid search term. It should have at least '.$min_wordlength.' characters and should not contain special characters.', 
'Sorry, no results found.' => 'Sorry, no results found.', 
/** views/documentation.php */ 
'Documentation' => 'Documentation', 
/** views/settings.php */ 
'Settings' => 'Settings', 
'Search function settings' => 'Search function settings', 
'Min. word length' => 'Min. word length', 
'Minimum char. length that a search term must have, before a search is carried out or not be ignored.' => 'Minimum char. length that a search term must have, before a search is carried out or not be ignored.', 
'No. of terms allowed' => 'No. of terms allowed', 
'Maximum number of terms that can be searched for. This setting relates to boolean search function.' => 'Maximum number of terms that can be searched for. This setting relates to boolean search function.', 
'Weight of title tag' => 'Weight of title tag', 
'Scoring weight of result, when search term is found in the title.' => 'Scoring weight of result, when search term is found in the title.', 
'Weight of meta tags' => 'Weight of meta tags', 
'Scoring weight of result, when search term is found in the meta description or meta keywords tag.' => 'Scoring weight of result, when search term is found in the meta description or meta keywords tag.', 
'Short description length' => 'Short description length', 
'Char. length of short description of each result, shown on search result page.' => 'Char. length of short description of each result, shown on search result page.', 
'Results per page' => 'Results per page', 
'Number of results to return per page on search results page.' => 'Number of results to return per page on search results page.', 
'Save' => 'Save', 
'You have modified this page. If you navigate away from this page without first saving your data, the changes will be lost.' => 'You have modified this page. If you navigate away from this page without first saving your data, the changes will be lost.', 
/** views/sidebar.php */ 
'Search plugin' => 'Search plugin', 
'The search plugin allows you to integrate a basic search function with boolean support.' => 'The search plugin allows you to integrate a basic search function with boolean support.', 
'See documentation for further details and use.' => 'See documentation for further details and use.', 
);
